/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 c:\Users\mouli\Mario-Bros.js\public\Coin.glb -o c:\Users\mouli\Mario-Bros.js\public\textures\Coin..js 
*/

import React, { useRef, useMemo, useLayoutEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGraph } from '@react-three/fiber'
import { SkeletonUtils } from 'three-stdlib'



export function Coin() {
  const { scene } = useGLTF('/Coin.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  useLayoutEffect(() => { 
    materials.CoinMat00.metalness = 0.6;
    materials.CoinMat00.roughness = 0;
  }, [materials.CoinMat00]);
  return (
    <group scale={1} dispose={null}>
      <primitive object={nodes.Coin_2} />
      <mesh geometry={nodes.Coin__CoinMat00.geometry} material={materials.CoinMat00} />
    </group>
  )
}

useGLTF.preload('/Coin.glb')
