/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 c:\Users\mouli\Mario-Bros.js\public\BlockEmpty.glb -o c:\Users\mouli\Mario-Bros.js\public\BlockEmpty..js 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BlockEmpty({position, showEmptyBlock}) {
  const { nodes, materials } = useGLTF('/BlockEmpty.glb')
  return (
    <group position={position} scale={0.99} dispose={null}>
      <primitive object={nodes.BlockEmpty_2} />
      <mesh geometry={nodes.BlockEmpty__BlockEmptyMat00.geometry} material={materials.BlockEmptyMat00} visible={showEmptyBlock} />
    </group>
  )
}

useGLTF.preload('/BlockEmpty.glb')
