/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 c:\Users\mouli\Mario-Bros.js\public\marioleveltest.glb -o c:\Users\mouli\Mario-Bros.js\public\marioleveltest..js 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { useStore } from "./store";
import { QuestionBlock } from "./blocks/QuestionBlock";
import { Brick } from "./blocks/Brick";

export function LevelTest() {
  const { nodes, materials } = useGLTF("/marioleveltest.glb");

  const { setNodes, setMaterials } = useStore();

  useEffect(() => {
    setNodes(nodes);
    setMaterials(materials);
  }, []);
  return (
    <>
      <group
        rotation={[0, -Math.PI / 2, 0]}
        position={[0, 0, 55]}
        dispose={null}
      >
        <QuestionBlock pos={[-49.359, 5.061, 0]} />
        <QuestionBlock pos={[-44.181, 5.061, 0]} mushroom={true} />
        <QuestionBlock pos={[-42.198, 5.061, 0]} />
        <QuestionBlock pos={[-43.142, 9.123, 0]} />
        <QuestionBlock pos={[16.992, 5.072, 0]} />
        <QuestionBlock pos={[33.495, 9.145, 0]} />
        <QuestionBlock pos={[45.941, 5.087, 0]} />
        <QuestionBlock pos={[49.008, 5.087, 0]} />
        <QuestionBlock pos={[52.105, 5.087, 0]} />
        <QuestionBlock pos={[49.044, 9.103, 0]}  mushroom={true}/>
        <QuestionBlock pos={[70.562, 9.136, 0]} />
        <QuestionBlock pos={[69.555, 9.136, 0]} />
        <QuestionBlock pos={[111.768, 5.067, 0]} />

        <Brick
          geometry={nodes.Brick001.geometry}
          material={materials.BlockBrickMat00}
          pos={[-45.205, 5.06, 0]}
        />
         <Brick
          geometry={nodes.Brick002.geometry}
          material={materials.BlockBrickMat00}
          pos={[-43.206, 5.06, 0]}
        />
        <Brick
          geometry={nodes.Brick003.geometry}
          material={materials.BlockBrickMat00}
          pos={[-41.163, 5.06, 0]}
        />
        <Brick
          geometry={nodes.Brick004.geometry}
          material={materials.BlockBrickMat00}
          pos={[15.986, 5.06, 0]}
        />
        <Brick
          geometry={nodes.Brick005.geometry}
          material={materials.BlockBrickMat00}
          pos={[19.147, 9.139, 0]}
        />
        <Brick
          geometry={nodes.Brick006.geometry}
          material={materials.BlockBrickMat00}
          pos={[33.504, 5.06, 0]}
        />
        <Brick
          geometry={nodes.Brick007.geometry}
          material={materials.BlockBrickMat00}
          pos={[39.69, 5.06, 0]}
        />
        <Brick
          geometry={nodes.Brick008.geometry}
          material={materials.BlockBrickMat00}
          pos={[40.714, 5.06, 0]}
        />
        <Brick
          geometry={nodes.Brick009.geometry}
          material={materials.BlockBrickMat00}
          pos={[58.361, 5.06, 0]}
        />
        <Brick
          geometry={nodes.Brick010.geometry}
          material={materials.BlockBrickMat00}
          pos={[69.57, 5.06, 0]}
        />
        <Brick
          geometry={nodes.Brick011.geometry}
          material={materials.BlockBrickMat00}
          pos={[70.625, 5.06, 0]}
        />
        <Brick
          geometry={nodes.Brick012.geometry}
          material={materials.BlockBrickMat00}
          pos={[109.716, 5.06, 0]}
        />
        <Brick
          geometry={nodes.Brick013.geometry}
          material={materials.BlockBrickMat00}
          pos={[110.724, 5.06, 0]}
        />
        <Brick
          geometry={nodes.Brick014.geometry}
          material={materials.BlockBrickMat00}
          pos={[112.802, 5.06, 0]}
        />
        <Brick
          geometry={nodes.Brick015.geometry}
          material={materials.BlockBrickMat00}
          pos={[30.419, 9.139, 0]}
        />
        <Brick
          geometry={nodes.Brick016.geometry}
          material={materials.BlockBrickMat00}
          pos={[61.444, 9.139, 0]}
        />
        <Brick
          geometry={nodes.Brick017.geometry}
          material={materials.BlockBrickMat00}
          pos={[68.547, 9.139, 0]}
        />
        <Brick
          geometry={nodes.Brick018.geometry}
          material={materials.BlockBrickMat00}
          pos={[71.589, 9.139, 0]}
        />
        <RigidBody colliders="hull" type="fixed" name={"pipe"} friction={0}>
        <group position={[-36.392, 2.613, 0]}>
          <mesh
            geometry={nodes.Dokan__DokanMat00.geometry}
            material={materials.DokanMat00}
          />
          <mesh
            geometry={nodes.Dokan__DokanMat00001.geometry}
            material={materials.DokanMat00}
            position={[10.316, 0.914, 0]}
          />
          <mesh
            geometry={nodes.Dokan__DokanMat00002.geometry}
            material={materials.DokanMat00}
            position={[18.574, 1.926, 0]}
          />
          <mesh
            geometry={nodes.Dokan__DokanMat00003.geometry}
            material={materials.DokanMat00}
            position={[29.967, 1.926, 0]}
          />
          <mesh
            geometry={nodes.Dokan__DokanMat00004.geometry}
            material={materials.DokanMat00}
            position={[141.318, 0, 0]}
          />
          <mesh
            geometry={nodes.Dokan__DokanMat00005.geometry}
            material={materials.DokanMat00}
            position={[157.825, 0, 0]}
          />
          <mesh
            geometry={nodes.Dokan__DokanMat01.geometry}
            material={materials.DokanMat00}
          />
        </group>
        </RigidBody>
        <RigidBody colliders="trimesh" type="fixed" name={"ground"} friction={5}>

        <group position={[74.737, 2.018, 0]}>
          <mesh
            geometry={nodes.BlockEmpty__BlockEmptyMat00001.geometry}
            material={materials.BlockEmptyMat00}
            position={[6.237, 3.132, 0]}
            rotation={[Math.PI, 0, Math.PI]}
          />
          <mesh
            geometry={nodes.BlockEmpty__BlockEmptyMat00002.geometry}
            material={materials.BlockEmptyMat00}
            position={[21.308, 3.132, 0]}
            rotation={[Math.PI, 0, Math.PI]}
          />
          <mesh
            geometry={nodes.BlockEmpty__BlockEmptyMat00003.geometry}
            material={materials.BlockEmptyMat00}
            position={[2.993, 3.132, 0]}
          />
          <mesh
            geometry={nodes.BlockEmpty__BlockEmptyMat00004.geometry}
            material={materials.BlockEmptyMat00}
            position={[17.923, 3.132, 0]}
          />
        </group>
        </RigidBody>
        <RigidBody colliders="trimesh" type="fixed" name={"ground"} friction={5}>

        <group position={[88.48, 2.014, 0]}>
          <mesh
            geometry={nodes.BlockEmpty__BlockEmptyMat00.geometry}
            material={materials["BlockEmptyMat00.001"]}
          />
          <mesh
            geometry={nodes.BlockEmpty__BlockEmptyMat00006.geometry}
            material={materials["BlockEmptyMat00.001"]}
            position={[34.854, 0, 0]}
          />
          <mesh
            geometry={nodes.BlockEmpty__BlockEmptyMat00014.geometry}
            material={materials["BlockEmptyMat00.001"]}
            position={[42.073, 7.023, 0]}
          />
        </group>
        </RigidBody>
        <RigidBody colliders="trimesh" type="fixed" name={"ground"} friction={5}>

        <group
          position={[140.535, 1.905, 0]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={2.207}
        >
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.008}>
            <mesh
              geometry={nodes.Base_Material_0.geometry}
              material={materials["Material.001"]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
            <mesh
              geometry={nodes.Flag_Flag_0.geometry}
              material={materials.Flag}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
            <mesh
              geometry={nodes.Goal_Brick_Brick_0.geometry}
              material={materials.Brick}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
            <mesh
              geometry={nodes.Pipe_Pipe_0.geometry}
              material={materials.Pipe}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
            <mesh
              geometry={nodes.Yellow_Ball_Yellow_ball_0.geometry}
              material={materials.Yellow_ball}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </group>
          
        </group>
        </RigidBody>

        <RigidBody colliders="trimesh" type="fixed" name={"ground"} friction={5}>

        <group scale={0.01}>
          <group scale={100}>
            <mesh
              geometry={
                nodes.nes_bldg_smb11_zeimport_poly12_XSIPOLYCLScastleside1_0
                  .geometry
              }
              material={materials["zeimport_poly12_XSIPOLYCLS.castleside1"]}
              position={[0, 0, -3.996]}
            />
            <mesh
              geometry={
                nodes.nes_bldg_smb11_zeimport_poly15_XSIPOLYCLScastleside_0
                  .geometry
              }
              material={materials["zeimport_poly15_XSIPOLYCLS.castleside"]}
              position={[0, 0, -3.996]}
            />
            <mesh
              geometry={
                nodes.nes_bldg_smb11_zeimport_poly17_XSIPOLYCLScastle_0.geometry
              }
              material={materials["zeimport_poly17_XSIPOLYCLS.castle"]}
              position={[0, 0, -3.996]}
            />
            <mesh
              geometry={
                nodes.nes_bldg_smb11_zeimport_poly5_XSIPOLYCLSground1_0.geometry
              }
              material={materials["material_0.001"]}
              position={[0, 0, -3.996]}
            />
          </group>
        </group>
        </RigidBody>
      </group>
    </>
  );
}

useGLTF.preload("/marioleveltest.glb");
